### ISSUE TITLE
iso-8601 datetime formatting

### ISSUE THREAD

**Issue by ThomasWaldmann** [letsmeet-click/letsmeet.click#45]
In the events list I get: "Jan. 28, 2016, 7 p.m. - Jan. 28, 2016, 10 p.m.".

https://xkcd.com/1179/

(and to add to that: the time format is HH:MM[:SS] with 24h)

**Comment by asmaps** [comment]
That xkcd does not match that time, because the month is written as text. The issue is, that if you only have numbers you cannot always know which one should be the year, month or day: 07-08-09... could be `August 7th, 2009`, `August 9th, 2007` or ..... when writing the month as text and the full year it's no problem. 12/24h time formatting is another thing, but it doesn't make times ambiguous so is just flavor thing. I personally like the "old" version more, like this people that don't know the ISO may not get which one is the month or day.

**Comment by asmaps** [comment]
Sources:
https://www.englishclub.com/vocabulary/time-date.htm

```
Note that another format exists which writes the date numerically in the order Year-Month-Day,
for example: 2016/03/14. This is rare in British or American English and
used mainly in very official or technical documents.
```

The old version would be variant C which is far more widespread in all day use.
